### ISSUE TITLE
ScrollMetricsManager.js:20 Uncaught TypeError: Class extends value undefined is not a constructor or null  at ./node_modules/@blockly/plugin-scroll-options/src/ScrollMetricsManager.js (ScrollMetricsManager.js:20:1)     at options.factory (react refresh:6:1)

### ISSUE THREAD

**Issue by painghtetaung** [rachel-fenichel/blockly-samples#1321] opened 2022-10-07 19:39 UTC
**Category**

**Component**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cpcallen** [comment] 2023-01-30 19:17
Hi @painghtetaung,

Can you provide more information about how to reproduce this error, please?

**Comment by maribethb** [comment] 2023-02-22 22:07
I can't reproduce this on v3.0.8. @painghtetaung please provide more information about how we can reproduce. Thanks!

**Comment by BeksOmega** [comment] 2023-05-16 16:16
Closing as cannot reproduce.

**Closed as completed by BeksOmega** 2023-05-16 16:16 UTC
Labels: type: bug
