### ISSUE TITLE
Custom blocks are not visible under category in react

### ISSUE THREAD

**Issue by iamkhan001** [rachel-fenichel/blockly-samples#1231] opened 2022-08-30 09:04 UTC
Hi there,

I have created some custom blocks using blockly react example in this repo. 
But i wanted to show them under custom category. But these blocks are not visible when I click on category name.

below is my code to add custom blocks 

```
const mathChangeJson = {
  "message0": "change %1 by %2",
  "args0": [
    {"type": "field_variable", "name": "VAR", "variable": "item", "variableTypes": [""]},
    {"type": "input_value", "name": "DELTA", "check": "Number"}
  ],
  "previousStatement": null,
  "nextStatement": null,
  "colour": 230
};

Blockly.Blocks['math_change'] = {
  init: () => {
    this.jsonInit(mathChangeJson);
    const thisBlock = this;
    this.setTooltip( () => {
      return 'Add a number to variable "%1".'.replace('%1',
          thisBlock.getFieldValue('VAR'));
    });
  }
};
```

below is my code where I'm trying to add custom block in category

```
      <BlocklyComponent 
      saveState = {saveState}
      updateState = {updateState}
      readOnly={readOnly} 
      trashcan={trashcan} media={'media/'}
        move={{
          scrollbars: false,
          drag: true,
          wheel: true
        }}
        initialXml={`
        <xml xmlns="http://www.w3.org/1999/xhtml">
        <Block type="controls_ifelse" x="0" y="0"></Block>
        </xml>`}>
      <Category name="Variables" categorystyle="variable_category" custom="VARIABLE_DYNAMIC" />
      <Category name="Functions" categorystyle="procedure_category" custom="PROCEDURE" />
      <sep/>
      <Category name="Temi" categorystyle="loop_category">
        <Block type="controls_if" />
        <Block type="math_change" />
      </Category>
    </BlocklyComponent>
```

Please help on this

**Comment by BeksOmega** [comment] 2022-09-01 20:35
Dupe of #1232

**Closed as completed by BeksOmega** 2022-09-01 20:35 UTC
Labels: type: bug
