### ISSUE TITLE
Republish codelabs to fix unpkg loading errors

### ISSUE THREAD

**Issue by selmen2004** [rachel-fenichel/blockly-samples#2429] opened 2024-07-31 02:15 UTC
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Component

getting-stared-codelab

### Description

when running codelab , it is pointed in 

https://blocklycodelabs.dev/codelabs/getting-started/index.html?index=..%2F..index#3

that you should add "https://unpkg.com/blockly" as a script ,
it loads a a script that tries to define "Blockly" but fails 

it works perfectly if we use : 
<script src="https://unpkg.com/blockly/blockly_compressed.js"></script>
    <script src="https://unpkg.com/blockly/blocks_compressed.js"></script>
    <script src="https://unpkg.com/blockly/javascript_compressed.js"></script>
    <script src="https://unpkg.com/blockly/msg/en.js"></script>

### Reproduction steps

1. download code lab source as instructed 
2. edit "index.html"
3. add "https://unpkg.com/blockly" as script 
4. run

### Stack trace

```shell
blockly:8 Uncaught 
TypeError: Cannot read properties of undefined (reading 'Msg')
    at blockly:8:55
    at blockly:10:2
(anonymous)	@	blockly:8
(anonymous)	@	blockly:10

main.js:67 Uncaught 
ReferenceError: Blockly is not defined
    at main.js:67:1
    at main.js:73:3
(anonymous)	@	main.js:67
(anonymous)	@	main.js:73
```

**Comment by cpcallen** [comment] 2024-08-02 16:45
Not sure how the instructions as given would have worked in the past, but in any case this is a dupe of #2378 which is already fixed; we just need to actually publish the codelabs which (it turns out ) we have not done recently.

**Comment by rachel-fenichel** [comment] 2024-08-23 16:39
Done.

**Closed as completed by rachel-fenichel** 2024-08-23 16:39 UTC
Labels: type: bug
