### ISSUE TITLE
Keyboard Navigation Plugin Fieldcolor Warning Message

### ISSUE THREAD

**Issue by changminbark** [rachel-fenichel/blockly-samples#2439] opened 2024-08-06 08:12 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Keyboard Navigation Plugin

### Description

I am currently getting the error message shown in the picture below whenever I run a test Blockly environment with the keyboard navigation plugin installed (in package.json). I am not 100% sure what is causing this, but I think it may have something to do with the fact that the keyboard navigation plugin uses Blockly.FieldColour, which is now deprecated. It seems that the FieldColour function has been separated to a different plugin, so the keyboard navigation plugin is not able to access this deprecated field/feature.

![image](https://github.com/user-attachments/assets/43a6df13-6ed7-4755-a344-caac4759184d)

### Reproduction steps

1. 
2. 
3.

### Screenshots

![image](https://github.com/user-attachments/assets/890710c1-7392-4729-9083-6aae774732ec)

**Comment by cpcallen** [comment] 2024-08-09 18:27
This appears to be a dupe of #2382, which was recently fixed and the fix should have been published yesterday in plugin version 0.6.7.  I'm going to close this but please reopen if you are able to reproduce in the most recent version!

**Closed as completed by cpcallen** 2024-08-09 18:27 UTC
Labels: type: bug
