### ISSUE TITLE
Plugin content highlight does not refresh when refrshing webpage

### ISSUE THREAD

**Issue by SebCanet** [rachel-fenichel/blockly-samples#2201] opened 2024-02-15 01:26 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Plugin content highlight

### Description

When using this plugin, and refresh webpage, only 'grey' background is visible and no more white rectangle. But if you move any block it comes back. It seems a new instance of plugin is loaded each time you refresh (because it's possible to invoke 'init' many times on same workspace).

### Reproduction steps

1. Use "https://google.github.io/blockly-samples/plugins/content-highlight/test/index.html"
2. Put a block
3. Refrsh with F5 or type enter in URL

**Comment by maribethb** [comment] 2024-02-21 21:22
Thanks for filing! This is a duplicate of #2175

**Closed as not planned by maribethb** 2024-02-21 21:22 UTC
Labels: type: bug

**Comment by SebCanet** [comment] 2024-02-23 08:50
Yeah, I understand why. Thanks.
