### ISSUE TITLE
Update readmes for field plugins

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1739] opened 2023-06-23 00:22 UTC
**Category**

 - Plugins

**Component**

field-angle
field-multiline
field-colour

**Describe the bug**

The readmes of the fields that we moved from core currently point to the devsite docs, which have not been updated to reflect the breaking changes made to the API.

**Expected behavior**

The readmes should document the differences between the APIs in core and the new APIs in the plugins.

**Comment by maribethb** [comment] 2023-06-23 01:50
I think the readmes should probably just document the fields entirely, and not just the differences from core (though a section outlining the differences would be useful for a while). This would be more consistent with the way other plugins work. And once we remove the fields from core, if you are a new developer trying to use these fields for the first time, it will be awkward to have documentation reference something that doesn't exist and then add changes on top of that.

But higher priority is at least documenting the differences before release.

**Comment by gonfunko** [comment] 2023-08-03 17:32
Duplicate of #1840.

**Closed as completed by gonfunko** 2023-08-03 17:32 UTC
Labels: type: bug, documentation
