### ISSUE TITLE
Toolbox Search is not working when category is created through xml

### ISSUE THREAD

**Issue by mugilanm7** [rachel-fenichel/blockly-samples#1939] opened 2023-09-20 09:55 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

Toolbox Search

https://github.com/google/blockly-samples/tree/master/plugins/toolbox-search

### Issue: 
   When category is created through xml search is not working for any blocks.  On investigating we could find the reason for this issue which is explained below

### Investigation:

- When category is created through xml  its blocks kind are set to "BLOCK" in **toolbox.ts line number 352 (const tagName = child.tagName.toUpperCase();)**

**toolbox**
```
function xmlToJsonArray(
  toolboxDef: Node | Node[] | NodeList,
): FlyoutItemInfoArray | ToolboxItemInfo[] {
  const arr = [];
  // If it is a node it will have children.
  // AnyDuringMigration because:  Property 'childNodes' does not exist on type
  // 'Node | NodeList | Node[]'.
  let childNodes = (toolboxDef as AnyDuringMigration).childNodes;
  if (!childNodes) {
    // Otherwise the toolboxDef is an array or collection.
    childNodes = toolboxDef;
  }
  for (let i = 0, child; (child = childNodes[i]); i++) {
    if (!child.tagName) {
      continue;
    }
    const obj = {};
    const tagName = child.tagName.toUpperCase();
    (obj as AnyDuringMigration)['kind'] = tagName;

    // Store the XML for a block.
    if (tagName === 'BLOCK') {
      (obj as AnyDuringMigration)['blockxml'] = child;
    } else if (child.childNodes && child.childNodes.length > 0) {
      // Get the contents of a category
      (obj as AnyDuringMigration)['contents'] = xmlToJsonArray(child);
    }

    // Add XML attributes to object
    addAttributes(child, obj);
    arr.push(obj);
  }
  // AnyDuringMigration because:  Type '{}[]' is not assignable to type
  // 'ToolboxItemInfo[] | FlyoutItemInfoArray'.
  return arr as AnyDuringMigration;
}
```
- And on toolbar search initialize on toolbox_search.ts in getAvailableBlocks method 
```
private getAvailableBlocks(
      schema: Blockly.utils.toolbox.ToolboxItemInfo, allBlocks: Set<string>) {
    if ('contents' in schema) {
      schema.contents.forEach((contents) => {
        this.getAvailableBlocks(contents, allBlocks);
      });
    } else if (schema.kind === 'block') {
      if ('type' in schema && schema.type) {
        allBlocks.add(schema.type);
      }
    }
  }
```
**schema.kind  is checked as 'block' in lowercase. so no blocks are added to search**

  

### Reproduction steps

1.Create categories with custom blocks through xml 
2. add toolbox search xml using 
`<category kind="search" name="search"></category>`

**Comment by BeksOmega** [comment] 2023-09-20 12:23
Thank you for filing :D This is a dupe of https://github.com/google/blockly-samples/issues/1925 The fix in https://github.com/google/blockly-samples/pull/1930 Should go out tomorrow!

**Closed as completed by BeksOmega** 2023-09-20 12:23 UTC
Labels: type: bug
