### ISSUE TITLE
Index dropdown items in the toolbox-search plugin

### ISSUE THREAD

**Issue by koenvanwijk** [rachel-fenichel/blockly-samples#2003] opened 2023-10-04 12:43 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

toolbox-search plugin

### Problem

I am frustrated when my toolbox search does not find the block eventhough it is an dropdown option on a block:
![image](https://github.com/google/blockly-samples/assets/8227977/5a4cedc6-d3cc-4a88-9df1-b0a7dacfce9c)

### Request

The search index should also index the dropdown items and even select that option on the block in the menu. 
![image](https://github.com/google/blockly-samples/assets/8227977/6e483c56-2c10-4558-8755-fa53891cef52)

**Comment by BeksOmega** [comment] 2023-10-04 15:37
Dupe of https://github.com/google/blockly-samples/issues/1940

**Closed as completed by BeksOmega** 2023-10-04 15:37 UTC
Labels: type: feature request
