### ISSUE TITLE
Workspace state is not saving in react

### ISSUE THREAD

**Issue by iamkhan001** [rachel-fenichel/blockly-samples#1230] opened 2022-08-30 08:58 UTC
Hi there,

I'm using google blockly with React. 
When I'm converting blocks to code and update state in react app, workspace stage gets cleared and it reset to inital state.
I want to save current state of workspace but when i try to do this i get error. but at same time whne i try to convert blocks to code, it works fine.

below is my code part where i convert blocks to code and try to get json to save workspace.

```
const generteCode = () => {
      const jsp = BlocklyJS.workspaceToCode(
        primaryWorkspace.current
      );
      const pyp = python.workspaceToCode(
        primaryWorkspace.current
      );
      const luap = lua.workspaceToCode(
        primaryWorkspace.current
      );
      const phpp = php.workspaceToCode(
        primaryWorkspace.current
      );
     

       const json = Blockly.serialization.workspaces.save(primaryWorkspace.current); //getting undefined error for primaryWorkspace.current
       console.log('json', json);
       setBlockState(json);

      setCodeJs(jsp);
      setCodePy(pyp);
      setCodeLua(luap);
      setCodePhp(phpp);
      setShowProgram(true);
  }
```
Please help on this.

**Comment by BeksOmega** [comment] 2022-09-01 20:35
Dupe of #1232

**Closed as completed by BeksOmega** 2022-09-01 20:35 UTC
Labels: type: bug
