### ISSUE TITLE
Enable linting and formatting in examples

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1981] opened 2023-09-26 19:59 UTC
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Component

all examples

### Problem

Current behavior: examples are not linted, nothing is formatted
After https://github.com/google/blockly-samples/pull/1946: examples are excluded from linting and formatting

We want to lint and format examples as well

### Request

1. Remove `examples` from the ignore list in `eslint.config.js`
2. Remove `examples` from the ignore list in `.prettierignore`
3. Potentially need to add new files to the ignore list(s) if there are any files in the examples that shouldn't be formatted. Commit all changes so far
4. Run `npm run lint:fix` and commit the changes.
5. Run `npm run format` and commit the changes.
6. Run `npm run lint`, manually fix any remaining lint errors or warnings, and commit the changes.

It is important that steps 4, 5, and 6 each be committed separately, as this will make reviewing and rebasing the PR easier.

Note that some examples specify their own lint command and I'm not sure how this will interact with the new flat config. If you attempt this process and find issues with linting any of the examples, let us know in the comments!

**Comment by alicialics** [comment] 2023-10-27 15:21
There were 1k+ eslint errors, but most of them were caused by a few select plugins (eg interpreter-demo).  Ignoring them brings down the number to 125 errors (and many more warnings).

It might be simpler to do it example by example to make it easier to review since not all of changes are trivial and its hard to guarantee a change is correct without actually running it and hopefully test what you've changed.

We can use the re-include pattern to ignore all examples but a project you are working on
https://eslint.org/docs/latest/use/configure/ignore
> Lines preceded by ! are negated patterns that re-include a pattern that was ignored by an earlier pattern.

**Comment by BeksOmega** [comment] 2023-11-21 19:09
Believe this was closed by #2070, correct me if I'm wrong @alicialics !

**Comment by alicialics** [comment] 2023-11-22 01:56
I think there are some work left over.  #2068 runs prettier on all example files as well as enabling eslint on *some* examples.  After #2068 is merged I think there are significant work in enabling eslint on the rest of examples.

**Closed as completed** 2024-01-30 23:15 UTC
Labels: type: feature request
